name: pmbo
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.5
  - numpy=1.21.2
  - pandas=0.24.2
  - scipy=1.7.1
  - scikit-learn=1.0.2
  - matplotlib=3.3.2
  - joblib=1.1.0
  - jupyter
  - pip
  - pip:
    - gpytorch==1.10
    - torch==1.12.1
    - torchvision==0.13.1
    - torchaudio==0.12.1
